### ISSUE TITLE
Immobilized, No Atari8 Graphics, Music Missing...

### ISSUE THREAD

**Issue by LREmery** [bob0bob/ARX#2]
1) All characters, (pre-.83 & new) are "Immobilized!". 
2) Cannot switch to Atari8 graphics anymore (option #5?).
3) Atari8 (original & best) version of "Let In The Light" is missing.  I mentioned this to Guilherme and referred him to the following link:
https://www.youtube.com/watch?v=D2ii1oUjlBw
Thank you very much for your hard work on this!  :-)

**Comment by bob0bob** [comment]
2.   in the c++ version you can only select that through the arx.ini file.   Just wanted to make sure you are doing it through the arx.ini.   The up coming Java version has the ability to select it at the main menu.  the C++ doesn't.  The original code loaded textures automatically at start.

![arx83](https://user-images.githubusercontent.com/30982580/36184564-23dee82a-10fa-11e8-9783-883274de2597.png)

**Comment by bob0bob** [comment]
1.  The immobilize, didn't appear to be on before I made changes.    He commented it out for some reason.  But I put it back in like the original game did.  It wouldn't let you carry everything.  You are limited to what you carry.  So if upgrading to 0.83.  it can be a shock to get that.  

net version will have the Devourer doing what he did based on your inventory.  I'm trying to get it to be more like the original game.  

You can't carry everything,  original had a limit.   Even so that when immobilized, you randomly start dropping items.  That is coming next.
Also, breaking of all weapon like the original is coming except for the special one only items.

Also,  encounters armor is working.  So you can't kill a ghost anymore with blunt weapons.  It is based on the original.  You need a magic weapon to kill a Devourer.   
The game just got a lot hard.

**Comment by bob0bob** [comment]
I'll try and capture the songs and get it in.   I remember more songs then it has.  
I got the title song into the Java Version.

Keep reporting them.  If you see any graphics or sounds missing from original. Please point them out.  I loved this game and want to get it back to the original and then expand it.

**Comment by LREmery** [comment]
Let In The Light:
https://www.youtube.com/watch?v=D2ii1oUjlBw

I'm sorry if I wasn't clear regarding the Immobilize issue.  I created a NEW, FRESH character using ONLY the .83 files straight from the .zip, and I was BORN "Immobilized!" at the Floating Gate, holding only 3 water, 3 food, and my Bare Hands!  Each character I create - and even load from upgraded .82-to-.83, I'm still Immobilized.  What have I done wrong?

**Comment by bob0bob** [comment]
Got it.  Its the clothes.  the calculation is wrong for it.  I'll get it done in a bit.

**Comment by bob0bob** [comment]
Got it.   check out 0.83.2 and let me know.  When it put clothing into player inventory, it didn't copy the items weight and what ever junk in memory at the position was the weight.

**Comment by bob0bob** [comment]
move the music into a different issue so we can close this item.

**Comment by LREmery** [comment]
"move the music into a different issue so we can close this item."

Please forgive my ignorance/retardedness, but I'm not sure how to do what you asked...

**Comment by LREmery** [comment]
Immobilization issue FIXED with .83.2!  Thanks!!  :-)

**Comment by bob0bob** [comment]
I created a new issue for the missing song, so we can close this issue.
